apiVersion: v1
kind: Service
metadata:
  name: ieap-api
  namespace: ieap
  labels:
    app.kubernetes.io/name: ieap
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app.kubernetes.io/name: ieap
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: ieap-api-headless
  namespace: ieap
  labels:
    app.kubernetes.io/name: ieap
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/name: ieap
    app.kubernetes.io/component: api
